Repository GrantBirki/issue-template-parser, pull requests merged in 2023-08, with the labels that each got.

#6 Replace apostrophe in JSON string
  parse.js
Labels: bug

#7 npm update and node version updates
  .node-version
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#8 Quotes tests
  fixtures/blank/form.yml
  fixtures/model-example/form.yml
  fixtures/model-example/issue.js
  fixtures/multiple-paragraphs/form.yml
  fixtures/readme-example/form.yml
  fixtures/scary-quotes/expected.json
  fixtures/scary-quotes/issue.js
  test.spec.js
Labels: enhancement
